# Generated by Django 5.0.3 on 2024-04-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='duratiion',
            new_name='duration',
        ),
    ]
